#use_frameworks!//不使用动态库

platform :ios, '8.0'

target 'MAGPSEmulator_Example' do
  pod 'MAGPSEmulator', :path => '../'
  pod 'AMap3DMap'

  target 'MAGPSEmulator_Tests' do
    inherit! :search_paths

    
  end
end
