#use_frameworks!//不使用动态库

platform :ios, '9.0'

target 'MAGPSEmulator_Example' do
  pod 'MAGPSEmulator', :path => '../'
  pod 'AMap3DMap', '~> 7.9.0'

  target 'MAGPSEmulator_Tests' do
    inherit! :search_paths

    
  end
end
